/**
 * Metadata registry for rich embeds (Twitter/X, Substack, etc.)
 *
 * AUTO-GENERATED by scripts/fetch-embeds.ts
 * Run `npm run fetch-embeds` to update.
 *
 * Last updated: 2026-01-15T00:25:11.263Z
 */

export interface TweetMetadata {
  type: 'tweet'
  authorName: string
  authorHandle: string
  authorAvatar: string
  text: string
  date: string
  url: string
}

export interface SubstackMetadata {
  type: 'substack'
  publicationName: string
  publicationLogo: string
  title: string
  description: string
  authorName: string
  url: string
}

export type EmbedMetadata = TweetMetadata | SubstackMetadata

/**
 * Registry of embed metadata, keyed by URL.
 */
export const embedRegistry: Record<string, EmbedMetadata> = {
  // Tweet by @karpathy
  'https://x.com/karpathy/status/2004607146781278521': {
    type: 'tweet',
    authorName: "Andrej Karpathy",
    authorHandle: "karpathy",
    authorAvatar: "https://pbs.twimg.com/profile_images/1296667294148382721/9Pr6XrPB_400x400.jpg",
    text: "I’ve never felt this much behind as a programmer. The profession is being dramatically refactored as the bits contributed by the programmer are increasingly sparse and between. I have a sense that I could be 10X more powerful if I just properly string together what has become",
    date: "Dec 26, 2025",
    url: "https://x.com/karpathy/status/2004607146781278521",
  },

  // Our Souls Need Proof of Work by Julie Zhuo
  'https://lg.substack.com/p/the-looking-glass-our-souls-need': {
    type: 'substack',
    publicationName: "The Looking Glass",
    publicationLogo: "https://substackcdn.com/image/fetch/$s_!f8qH!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fcbadfdf8-3c2d-415f-9d84-7751ef986cda%2Fapple-touch-icon-57x57.png",
    title: "Our Souls Need Proof of Work",
    description: "Dear Readers: I’m starting a series exploring AI and how it might change us — the way we work and learn and relate to the world. There is so much to explore! Expect more frequency of posts going forward.",
    authorName: "Julie Zhuo",
    url: "https://lg.substack.com/p/the-looking-glass-our-souls-need",
  },

}

/**
 * Look up metadata for a given URL.
 * Matches by prefix to handle URL variations (query params, etc.)
 */
export function getEmbedMetadata(url: string): EmbedMetadata | null {
  // Try exact match first
  if (embedRegistry[url]) {
    return embedRegistry[url]
  }

  // Try prefix match (handles query params, fragments, etc.)
  const baseUrl = url.split('?')[0]
  for (const [key, metadata] of Object.entries(embedRegistry)) {
    const keyBase = key.split('?')[0]
    if (baseUrl === keyBase || baseUrl.startsWith(keyBase) || keyBase.startsWith(baseUrl)) {
      return metadata
    }
  }

  return null
}
